export const featureAccessData = [
  {
    title: "Dashboard",
    action: true,
    path: "/dashboard",
    nested: [],
  },
  {
    title: "Teamchat",
    action: true,
    path: "/dashboard/teamchat",
    nested: [],
  },
  {
    title: "Kundensuche",
    action: true,
    path: "/dashboard/customers",
    nested: [],
  },
  {
    title: "Neukundenerstellung",
    action: true,
    path: "/dashboard/neukundenerstellung",
    nested: [],
  },
  {
    title: "Einlagenaufträge",
    action: true,
    path: "/dashboard/orders",
    nested: [],
  },
  {
    title: "Maßschuhaufträge",
    action: true,
    path: "/dashboard/massschuhauftraege",
    nested: [],
  },
  {
    title: "Maßschäfte",
    action: true,
    path: "/dashboard/custom-shafts",
    nested: [],
  },
  {
    title: "Produktverwaltung",
    action: true,
    path: "/dashboard/lager",
    nested: [],
  },
  {
    title: "Sammelbestellungen",
    action: true,
    path: "/dashboard/group-orders",
    nested: [],
  },
  {
    title: "Nachrichten",
    action: true,
    path: "/dashboard/email/inbox",
    nested: [],
  },
  {
    title: "Terminkalender",
    action: true,
    path: "/dashboard/calendar",
    nested: [],
  },
  {
    title: "Monatsstatistik",
    action: true,
    path: "/dashboard/monatsstatistik",
    nested: [],
  },
  {
    title: "Mitarbeitercontrolling",
    action: true,
    path: "/dashboard/mitarbeitercontrolling",
    nested: [],
  },
  {
    title: "Einlagencontrolling",
    action: true,
    path: "/dashboard/einlagencontrolling",
    nested: [],
  },
  {
    title: "Fußübungen",
    action: true,
    path: "/dashboard/foot-exercises",
    nested: [],
  },
  {
    title: "Musterzettel",
    action: true,
    path: "/dashboard/musterzettel",
    nested: [],
  },
  {
    title: "Users",
    action: true,
    path: "/dashboard/users",
    nested: [],
  },
  {
    title: "Einstellungen",
    action: true,
    path: "/dashboard/settings",
    nested: [
      {
        title: "Grundeinstellungen",
        action: true,
        path: "/dashboard/settings-profile",
      },
      {
        title: "Backup Einstellungen",
        action: true,
        path: "/dashboard/settings-profile/backup",
      },
      {
        title: "Kundenkommunikation",
        action: true,
        path: "/dashboard/settings-profile/communication",
      },
      {
        title: "Werkstattzettel",
        action: true,
        path: "/dashboard/settings-profile/werkstattzettel",
      },
      {
        title: "Benachrichtigungen",
        action: true,
        path: "/dashboard/settings-profile/benachrichtigungen",
      },
      {
        title: "Lagereinstellungen",
        action: true,
        path: "/dashboard/settings-profile/notifications",
      },
      {
        title: "Preisverwaltung",
        action: true,
        path: "/dashboard/settings-profile/preisverwaltung",
      },
      {
        title: "Software Scanstation",
        action: true,
        path: "/dashboard/settings-profile/software-scanstation",
      },
      {
        title: "Design & Logo",
        action: true,
        path: "/dashboard/settings-profile/design",
      },
      {
        title: "Passwort ändern",
        action: true,
        path: "/dashboard/settings-profile/changes-password",
      },
      {
        title: "Sprache",
        action: true,
        path: "/dashboard/settings-profile/sprache",
      },
      {
        title: "Fragen",
        action: true,
        path: "/dashboard/settings-profile/fragen",
      },
      {
        title: "Automatische Orders",
        action: true,
        path: "/dashboard/settings-profile/automatische-orders",
      },
    ],
  },
];
